[package]
name = "minifb"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = { version = "0.20", features = ["x11"] }
image = { version = "0.23", features = ["jpeg_rayon"] }
png = "0.17.5"
