[package]
name = "vidir"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
tempfile = "3.2.0"
fs_extra = "1.2.0"
regex = "1.5.4"
lazy_static = "1.4.0"
itertools = "0.10.1"
