[package]
name = "gh_issues"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octocrab = "0.13"

tokio = { version = "*", default-features = false, features = ["macros", "rt-multi-thread", "time"] }
