[package]
name = "get_color"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
ansi_term = "0.12"
rand = "0.8"
