[package]
name = "http_download"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
once_cell = "1.8"
hyper-tls = "0.5.0"
async-recursion = "0.3.2"
futures = "0.3.21"
sysinfo = "0.23.11"
