[package]
name = "audio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
cpal = "0.13.5"
hound = "3.4.0"
radio = "0.11.1"
ringbuf = "0.2.8"
rodio = "0.15.0"
