[package]
name = "fdroot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
procfs = "0.12.0"
strsim = "0.10.0"
