[package]
name = "music_tag"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
taglib = "1.0.0"
toml = "0.5.8"
serde = { version = "1.0.125", features = ["derive"] }
#tempfile = "3.2.0"
